[package]
name = "hira"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
tokio = { version = "1.0", features = ["macros","io-util","sync","rt-multi-thread"] }
serde_json = "*"
lambda_runtime = "*"
serde = { version = "1.0", features = ["derive"]}

[lib]
proc-macro = true
