[workspace]
members = [
    "hira",
    "hira_lib",
    "real_world_examples",
]

# compile dependencies in release mode
[profile.dev.package.'*']
opt-level = 3

[profile.release.package.'*']
opt-level = 3
