[package]
name = "dotenv_reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hira_lib = { path = "../../hira_lib" }
hira = { path = "../../hira" }
sapp-jsutils = "0.1"
