[package]
name = "aws_cfn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hira = { path = "../../hira" }
hira_lib = { path = "../../hira_lib" }
