[book]
authors = ["nikita-skobov"]
language = "en"
multilingual = false
src = "src"
title = "Hira"

[rust]
edition = "2021"

[output.html]
additional-css = ["index.css"]
git-repository-url = "https://github.com/nikita-skobov/hira"

[output.html.playground]
editable = false         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = false           # includes the JavaScript for the code editor
line-numbers = false     # displays line numbers for editable code
runnable = false          # displays a run button for rust code
