name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wasm
      run: rustup target add wasm32-unknown-unknown
    - name: tests
      run: cargo test -p hira_lib -- --test-threads=1
