name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_publish_book:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wasm
      run: rustup target add wasm32-unknown-unknown
    - name: Install mdbook
      run: |
        mkdir bin
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.30/mdbook-v0.4.30-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        echo "$(pwd)/bin" >> ${GITHUB_PATH}
    - name: Test book
      shell: bash
      run: cd book && ./test.sh
#     - name: Create release
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         tag: ${{ env.MY_DATE }}
#       run: |
#         zip -j hira.zip ./target/x86_64-unknown-linux-musl/release/hira_cli
#         gh release create "$tag" hira.zip
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wasm
      run: rustup target add wasm32-unknown-unknown
    - name: tests
      run: cargo test -p hira_lib -- --test-threads=1
  build_and_publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wasm
      run: rustup target add wasm32-unknown-unknown
    - name: Install cross
      uses: taiki-e/install-action@v2
      with:
        tool: cross
    - name: Build Hira CLI
      shell: bash
      run: cross build --release -p hira_cli --target=x86_64-unknown-linux-musl
    - name: get timestamp
      run: echo "MY_DATE=$(date '+%Y-%m-%dT%H')" >> $GITHUB_ENV
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.MY_DATE }}
      run: |
        zip -j hira.zip ./target/x86_64-unknown-linux-musl/release/hira_cli
        gh release create "$tag" hira.zip

