name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wasm
      run: rustup target add wasm32-unknown-unknown
    - name: tests
      run: cargo test -p hira_lib -- --test-threads=1
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wasm
      run: rustup target add wasm32-unknown-unknown
    - name: Install cross
      if: matrix.job.use-cross
      uses: taiki-e/install-action@v2
      with:
        tool: cross
    - name: Build Hira CLI
      shell: bash
      run: cross build --release -p hira_cli --target=x86_64-unknown-linux-musl
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: hira
        # A file, directory or wildcard pattern that describes what to upload
        path: ./target/x86_64-unknown-linux-musl/release/hira_cli
